### ISSUE TITLE
Turbine mk x put down on ground problem

### ISSUE THREAD

**Issue by nogamenofun98** [huanghongxun/WaterPower#10]
i create a turbine mk x (i forgot the level but i know it will generate 8192 eu/t)
but when i put it down....it turn to turbine that generate 512 eu/t
i just put it on the ground, no put it on the reservoir block yet..
so is it a bug or need to put on the reservoir block in order to show correct eu/t value?

version:
WaterPower-1.7.10-0.3j
industrialcraft-2-2.2.736-experimental

**Comment by huanghongxun** [comment]
fixed
