### ISSUE TITLE
IE compat issue (?)

### ISSUE THREAD

**Issue by accessdenied0** [huanghongxun/WaterPower#14]
Dear @huanghongxun,

I added your latest version of waterpower to my minecraft and I got a Issue with your IE compat.

Yes, I use the latest IE (0.5.4) and WP (1.7.10-0.3n) versions. Here the report: http://pastebin.com/bNButXgR

I hope you can help,

access_denied

**Comment by huanghongxun** [comment]
sorry 0.3n could only support IE 0.4.x
0.3o updated to 0.5.x

**Comment by accessdenied0** [comment]
@huanghongxun,

No problem, but I guess you missed more than one update? Or is this maybe my fault: http://pastebin.com/D9RDRPBd It seems to be another compat error.

access_denied

**Comment by huanghongxun** [comment]
Um... I forgot to remove some recipes that used IC2 items.
0.3o-hotfix fixed.
