### ISSUE TITLE
AOBD crash with latest WaterPower 0.3q

### ISSUE THREAD

**Issue by walkerjonny** [huanghongxun/WaterPower#16]
Hi,
I'm getting this AOBD related startup crash when the latest WaterPower 0.3q is installed.
http://pastebin.com/5ZyRJSfQ
The former version works fine.
FYI: Tinkers Construct updated to 1.8.8 about two days ago. Maybe there are also some changes that affect this. However I tested with Tinkers Construct 1.8.7 and 1.8.8 and the crash disappeared only when switching back to the former WaterPower version.

**Comment by huanghongxun** [comment]
You can downgrade AOBD.

**Comment by walkerjonny** [comment]
Why?
It works already with the former WaterPower build. This issue happens only with the newest WaterPower build 0.3q. Build 0.3p works fine so far with both the newest Tinkers Construct and AOBD.
The last AOBD build is from September, the 19th, and switching back might affect some other well known mods that have been updated in the meanwhile - like Tinkers Construct for example.
Maybe you have changed something within your mod regarding Magnetite ore/block...

**Comment by tecer0** [comment]
same issue, can't downgrade AOBD, i hope you can fix that.

**Comment by huanghongxun** [comment]
0.3r might fix this problem.

**Comment by walkerjonny** [comment]
Yes it does. Thank you very much for fixing it!
