### ISSUE TITLE
Ore Dictionary + Crafting Recipes

### ISSUE THREAD

**Issue by steelshot** [huanghongxun/WaterPower#24]
I've noticed that the mod ores are not using the ore dictionary properly.
At this moment the ores are
-Monazite
-Vanadium
-Manganese
-Magnet
-Zync

they should be
-oreMonazite
-oreVanadium
-oreManganese
-oreMagnet
-oreZync

Also i've noticed alot of recipes are not showing up on nei, multiple rotors(almost every single one, aroud 7 are only craftable), range plugin upgrades.

**Comment by steelshot** [comment]
Also MJ should be removed as a power API no one uses it anymore, and also what do HU and KU stand for?

**Comment by huanghongxun** [comment]
Will fix the ore dictionary problem.
MJ has been removed in code. But I didn't removed the sign in game. All energy units have been stored as their IDs. If I remove MJ, the IDs will get mixed up.

**Comment by huanghongxun** [comment]
Crafting recipes: most of rotors can only been crafted by GregTech materials. If you installed some mod producing materials like chromium or titanium, you could craft them.
