### ISSUE TITLE
每次重新进入游戏水轮机发电量会变小很多但是水库是满了

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [huanghongxun/WaterPower#41]
![2017-06-24_11 37 40](https://user-images.githubusercontent.com/20567492/27505433-3f9a5ce2-58d2-11e7-821c-d4ad05d228b5.png)
水库
![2017-06-24_11 37 42](https://user-images.githubusercontent.com/20567492/27505431-3f8cd78e-58d2-11e7-8dd5-25652e9d58b0.png)
重新进游戏后
![2017-06-24_11 37 52](https://user-images.githubusercontent.com/20567492/27505432-3f8d8d0a-58d2-11e7-8ac5-f332cdbdfd10.png)
把水轮机拆掉重新放置
![2017-06-24_11 38 05](https://user-images.githubusercontent.com/20567492/27505434-3fa22ce2-58d2-11e7-871f-3da6d2e06867.png)
顺便说下不支持TD的管道，这么高的发电量不能用TD简直了

**Comment by mgdgfbhevdyeh** [comment]
是我姿势不对吗？

**Comment by huanghongxun** [comment]
请尝试一下0.5.1
注意与0.4.x的世界不兼容

**Comment by mgdgfbhevdyeh** [comment]
fixed

**Comment by mgdgfbhevdyeh** [comment]
![2017-07-07_11 18 21](https://user-images.githubusercontent.com/20567492/27942040-a2f0153c-6306-11e7-8a19-e28a636f0d49.png)
dalao负数是什么情况？

**Comment by huanghongxun** [comment]
大概是。。。爆数据类型了。。

**Comment by mgdgfbhevdyeh** [comment]
so...又是个BUG。。。。

**Comment by mgdgfbhevdyeh** [comment]
BUG POWER;-0

**Comment by mgdgfbhevdyeh** [comment]
我试了下几乎所有水库都有负数BUG

**Comment by huanghongxun** [comment]
power是？

**Comment by mgdgfbhevdyeh** [comment]
![2017-07-11_18 15 42](https://user-images.githubusercontent.com/20567492/28063881-3bb5cc6a-6665-11e7-877f-1dc403f52319.png)
![2017-07-11_18 15 45](https://user-images.githubusercontent.com/20567492/28063879-3b9e880c-6665-11e7-80dd-c945d2a3486a.png)
![2017-07-11_18 15 49](https://user-images.githubusercontent.com/20567492/28063880-3badec16-6665-11e7-980f-34db336b0701.png)
我来服你这BUG修复啦！@huanghongxun

**Comment by huanghongxun** [comment]
不能复现水轮机负值的问题

**Comment by mgdgfbhevdyeh** [comment]
1.10.2,forge 2297

**Comment by huanghongxun** [comment]
try 0.5.4?

**Comment by mgdgfbhevdyeh** [comment]
it's fixed :)

**Comment by mgdgfbhevdyeh** [comment]
感觉SF附体，我又来汇报BUG了2333333333
![2017-07-12_08 23 37](https://user-images.githubusercontent.com/20567492/28096483-a7327094-66db-11e7-87d3-822c3de23190.png)
这个什么锯木机有问题，它第一次锯的确是6x，但是第二次开始一个原木只能锯一块木板

**Comment by huanghongxun** [comment]
建议下一次发bug的时候新开一个页面
我觉得挺好的，就缺测试人员呢233

**Comment by huanghongxun** [comment]
哎呀我真的是太菜了，复制代码都能漏东西

**Comment by huanghongxun** [comment]
不如来一发bug盛宴，这个bug发0.5.5感觉没必要
