### ISSUE TITLE
Server crash inserting ore into grinder on MC 1.12

### ISSUE THREAD

**Issue by jc2xs** [huanghongxun/WaterPower#44]
My server crashed when someone was using a vanilla hopper to insert iron ore into a water powered grinder.  We are using version 0.5.4 of WaterPower and Forgelin 1.5.0

Crash Report:  https://pastebin.com/VX1Ws37D

**Comment by huanghongxun** [comment]
Hello!

Thank you for your reporting.
This issue should be fixed in 0.5.5, please have a try.

Regards.

**Comment by jc2xs** [comment]
Thanks you for the quick response.  I'll let the pack dev know.
