### ISSUE TITLE
Hammer only has one use

### ISSUE THREAD

**Issue by cursinorock** [huanghongxun/WaterPower#48]
Hammer only has one use, recipes after first use do not generate anything. (meta data error?)

![2017-08-01_14 49 58](https://user-images.githubusercontent.com/24946430/28839069-d0e65944-76c8-11e7-8972-76e959639e90.png)

![2017-08-01_14 50 15](https://user-images.githubusercontent.com/24946430/28839075-d5ba5cd6-76c8-11e7-8d1c-61020488426e.png)

Tinkers table or not, same error.

version MC 1.11.2
version Forge 1.11.2-forge1.11.2-13.20.1.2429
version Mod WaterPower-1.11.2-0.5.6

**Comment by huanghongxun** [comment]
Thank you for your reporting this issue.
Yes I did forget to "generalize" of metadata of wooden hammer.
Fixed in 0.5.7
