### ISSUE TITLE
1.12 - invalid shaped recipe crash

### ISSUE THREAD

**Issue by Seth0067** [huanghongxun/WaterPower#49]
Any idea what I can do about this?  This may be some kind of mod conflict as I encountered this only after installing a few other mods (Mekanism for one). Before this the game loaded and the error did not occur.

[crash log](https://pastebin.com/G6EvyAPY)

**Comment by huanghongxun** [comment]
Yes, this is caused by missing IC2 requirement.
0.5.8 should fix this.

Regards.
