### ISSUE TITLE
The name of a class is not changed,so my minecraft was crashed.

### ISSUE THREAD

**Issue by LasmGratel** [huanghongxun/WaterPower#5]
This mod has changed name to WaterCraft,but some code was still Advanced Watermills,so it crashed.(code using org.jackhuang.compactwatermills.client.gui.CreativeTabCompactWatermills,but it's CreativeTabWaterCraft.)

**Comment by huanghongxun** [comment]
Some crash-reports would be better.

**Comment by huanghongxun** [comment]
The latest version would be fine.
